### ISSUE TITLE
Winboard protocol: reply move may be invalidated by commands

### ISSUE THREAD

**Issue by losos0** [jdart1/arasan-chess#48] opened 2023-04-20 08:23 UTC
https://github.com/jdart1/arasan-chess/blob/00843c41fbe69db4ad9c47ea274b718a9f20e011/src/protocol.cpp#L2825-L2831

Before executing a chosen reply move, check_pending is called which may execute various commands. Many of these commands (e.g. `undo`, `remove`, `go`) may change the board state, rendering the chosen move invalid.

For example, the following input (from a file) results in an assertion failure:
```
xboard
protover 2
usermove e4
undo
```

**Comment by jdart1** [comment] 2023-04-20 20:45
I have not been able to reproduce an assertion failure using the commands from a file you gave.
Note also: the part of code that is quoted relates to processing after a ponder search completed. "undo" would not be expected at that point. The CECP spec says "If the user asks to back up one move, xboard will send you the "undo" command. xboard will not send this command without putting you in "force" mode first, so you don't have to worry about what should happen if the user asks to undo a move your engine made." Line 2827 ensures the move is not sent by the engine for execution if the engine is in force mode.

**Comment by losos0** [comment] 2023-04-21 04:17
Yeah I figured it's probably not valid usage of the protocol; I just stumbled onto this case by accident while trying to reproduce another bug.


> I have not been able to reproduce an assertion failure using the commands from a file you gave.

Hmm do you have an opening book set up? Maybe the engine can only crash here if it does an actual search. The debug output looks like this:
```
$ ./arasanx-64 -t < crash.txt
Arasan 23.4 Copyright 1994-2022 by Jon Dart. All Rights Reserved.
in do_all_pending
out of do_all_pending, list size=0
in do_all_pending
pending command(a): xboard
do_command: xboard
move text = xboard
out of ponder loop
out of do_all_pending, list size=0
in do_all_pending
pending command(a): protover 2
do_command: protover 2
feature name=1 setboard=1 san=1 usermove=1 ping=1 ics=1 playother=0 sigint=0 colors=0 analyze=1 debug=1 memory=1 smp=1 variants="normal" egt="syzygy" option="Favor frequent book moves -spin 50 1 100" option="Favor best book moves -spin 50 1 100" option="Favor high-weighted book moves -spin 100 1 100" option="Randomize book moves -spin 50 1 100" option="Can resign -check 1" option="Resign threshold -spin -500 -1000 0" option="Position learning -check 1" option="Strength -spin 100 0 100" option="Use NNUE -check 1" option="NNUE file -string " option="Move overhead -spin 30 0 1000" myname="Arasan 23.4"
feature done=0
# warning: no NNUE file path was set, network not loaded
# warning: opening book not found or invalid
feature done=1
# out of do_all_pending, list size=0
# in do_all_pending
# pending command(a): usermove e4
# do_command: usermove e4
# move text = e4
# got move: e4
# execute_move: e2-e4
# in search()
#  time_limit=100000000 movestogo=0
# time_target = 10
# xtra time = 0
# command in search: undo
# out of search loop, move= e7-e6
# waiting for thread completion
# thread 0 depth=0 score=+0.01 failHigh=0 failLow=0 pv=e6
# best thread: depth=0 score=+0.01 fail high=0 fail low=0 pv=e6
# search done : move = e7-e6
# state = 0
# game_end = 0
# in check_pending
# erasing undo
# calling do_command from check_pending
# do_command: undo
arasanx-64: /mnt/c/Users/qchess/arasan-chess/src/board.cpp:877: void Board::doMove(Move, NodeInfo*): Assertion `getMaterial(sideToMove()).pawnCount() == (int)pawn_bits[side].bitCount()' failed.
Aborted
```

**Comment by jdart1** [comment] 2023-04-22 15:11
This is reproducible on Linux without the opening book. However, I am going to close this because there is no issue when the commands are sent in a way that corresponds to the CECP standard. If you put "force" before "undo," there is no assertion failure.

**Closed** 2023-04-22 15:12 UTC
